import React, { useState, useEffect } from 'react'

import SwaggerUI from "swagger-ui-react";
import "swagger-ui-react/swagger-ui.css";

// URLSearchParams

export default function ApiDocSwagger() {

  const [manifest, setManifest] = useState({});
  const [source, setSource] = useState();

  useEffect(() => {

    // fetch('/manifest.json', {method: 'GET'})
    //   .then(response => response.json())
    //   .then(data => {
    //     setManifest(data);
    //     console.log(data);
    //   });

    let search = window.location.search;
    let urlParams = new URLSearchParams(search);
    let sourceUrl = urlParams.get('source');
    console.log('source:', sourceUrl);
    setSource(sourceUrl);

  }, []);

  function ApiList(props) {
    console.log('props.manifest:', JSON.stringify(props.manifest, null, 2));
    return (
      <ul>
      {(props.manifest) && (props.manifest.apis) 
        && props.manifest.apis.map( (api) => 
        <li key={api.name}><a href={'/?source='+api.specUrl}>{api.name}</a></li>
      )}
      </ul>
    )
  }

  function ApiDocComponent() {
    if (source) {
      return (
      <>
        {/* <div>Documentation generated by <a href="https://swagger.io/docs/open-source-tools/swagger-ui/">Swagger UI</a></div> */}
        <SwaggerUI url={ source } />
      </>
      );
    }
    return <div>Provide OpenAPI spec source in the query param</div>;
  }

  return (
    <div>
      <ApiDocComponent />
      <ApiList manifest={manifest} ></ApiList>
    </div>
  )
}
