/**
 * Script that pushes site content to Algolia index.
 * The script relies on json files generated by the template files 
 * ./src/api/pages-json.njk, and 
 * ./src/api/posts-json.njk
 * 
 * When adding to the pipeline, make sure to configure the envs
 * ALGOLIA_APP_ID and 
 * ALGOLIA_ADMIN_API_kEY
 */
require('dotenv').config();
const fs = require('fs');
const algoliasearch = require('algoliasearch');

const ALGOLIA_APP_ID = process.env.ALGOLIA_APP_ID;
const ALGOLIA_ADMIN_API_KEY = process.env.ALGOLIA_ADMIN_API_KEY;

console.log(`Initializing Algolia client with ALGOLIA_APP_ID=${ALGOLIA_APP_ID}`);
const client = algoliasearch(ALGOLIA_APP_ID, ALGOLIA_ADMIN_API_KEY);
const index = client.initIndex(process.env.ALGOLIA_INDEX_NAME);

const API_PATH = './_site/api';

function readJson(path) {
    let rawdata = fs.readFileSync(path);
    return JSON.parse(rawdata);
}

async function pushToIndex(...dataFilePaths) {
    for (dataFilePath of dataFilePaths) {
        console.log(`Reading objects from file: ${dataFilePath}`);
        const json = readJson(dataFilePath);

        console.log(`Pushing ${json.length} objects...`);
        try {
            await index.saveObjects(json);
        } catch (error) {
            console.error('Error while pushing: ' + error);
        }
    }

    console.log("Pushing objects completed.");
}

(async() => {
    await pushToIndex(`${API_PATH}/pages.json`, `${API_PATH}/posts.json`);
})();